[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
]
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.5",
    "playwright>=1.63.0",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
]

[project.scripts]
test = "test:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
